version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_URL_BASE_DB: "postgres://myuser:mypassword@db:5432/mydatabase?sslmode=disable"
      INTERVAL_SECONDS: "60"
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - ./data:/app/data  # если требуется для доступа к XLSX файлам
    restart: on-failure

volumes:
  db_data:
