version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9090:80" 
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./postgres/servers.json:/pgadmin4/servers.json 
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: ./api/dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data 
    restart: on-failure

  app-web:
    build: ./web
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:
