# Build stage
FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -s' -o server ./api/server.go
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-w -s' -o main ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates && \
    mkdir -p /tmp && chmod 777 /tmp && \
    mkdir -p /app/data && chmod 777 /app/data

WORKDIR /root/

COPY --from=builder /app/server .
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./server"]