FROM golang:1.22 AS builder

WORKDIR /app

COPY ../ ./

RUN go mod tidy


RUN go build -o app .


FROM alpine:latest

RUN apk --no-cache add ca-certificates


COPY --from=builder /app/app /usr/local/bin/app


WORKDIR /app


CMD ["app"]
